---
title: "Logarithmic_exponential_Cruves"
author: "Serdar Korur"
date: "11/30/2019"
output: html_document
---

```{r}
library(tidyverse)
days <- 1:380
b <- rep(1.01, 380)
results <- b^days
logx_b <- log(days, b)
logexp <- data.frame(days, b, results, logx_b)


logexp %>% 
  ggplot(aes(x=days, y=results)) +
  geom_line(size=3, color = "red") + 
  theme_classic() +
   theme(text = element_text(size=16), 
         plot.title =element_text(hjust=0.5)) +
  labs(title = "Improve 1% everyday", y = "Cumulative improvement") + scale_y_continuous(labels = function(x) paste0(x, "00%")) + geom_point(aes(x=365, y=37.78), size=5)
  
# geom_hline(yintercept=37.5, lty=2) + geom_vline(xintercept = 365, lty=2)

logexp %>% 
  ggplot(aes(x=days, y=logx_b)) + 
  geom_line() +
  theme_classic() + 
  theme(text = element_text(size=16), 
         plot.title =element_text(hjust=0.5)) +
  labs(title = "Logarithmic growth") 
```


```{r, parkinsons law, with gamma distribution functionr}
library(ggplot2)
library(MASS)

# Generate gamma rvs

x <- rgamma(100000, shape = 3, rate = 0.2)

den <- density(x)

dat <- data.frame(x = den$x, y = den$y)

# Plot density as points

ggplot(data = dat, aes(x = x, y = y)) + 
  geom_area(fill="lightblue") +
  theme_classic() +
  theme(text = element_text(size=16), 
         plot.title =element_text(hjust=0.5)) +
  labs(title = "Parkinson's Law", x = "time allowed", y = "effort") + coord_cartesian(xlim = c(0, 50))

vec <- dat$y
```

```{r, Parkinson's Law, not easy}
library(tidyverse)
# Parkinson's Law

# effort = x = (2k^m+ p) / n 
 
# Where m is equal to time.
# n is effective units being administered

days <- 1:100
p <- 10
n <- 50
k <- 100:1
effort <- ((2*(k^days))+p)/n

park <- data.frame(days, effort)
park %>% ggplot(aes(x=days, y=effort)) + geom_point()
```

