---
title: "Privacy_policy"
author: "Dataatomic"
date: "4/20/2020"
output: html_document
---

# Overview

Dataatomic.com (“Dataatomic”, “we”, “us” or “our”) is committed to protecting your privacy. This Privacy Policy applies to the information that we obtain through your use of our products and/or services, our websites, including tools.dataatomic.com & www.dataatomic.com or when you otherwise interact with Dataatomic apps. This policy sets forth our policies and procedures regarding the collection, use and disclosure of Personal Information we receive from you. By using our products, services and/or Websites, you consent to the collection, transfer, processing, storage, disclosure and other uses described in this Privacy Policy. If you do not agree to the terms set forth herein, please do not use our products, services or Websites.

Please take the time to read this Privacy Policy. Unless stated otherwise, our current Privacy Policy applies to all personal information (“Personal Information”) you have provided to us.

# Changes to this Privacy Policy

We may change this Privacy Policy from time to time. If we make any changes, we will notify you by revising the “Last Updated” date at the top of this Privacy Policy and, in some cases, where appropriate we may provide you with additional notice (such as adding a statement to the login screen or sending you an email notification). We encourage you to review our Privacy Policy whenever you use our products, services and/or Websites to stay informed about our information practices and the ways you can help protect your privacy. Using our products, services and/or Websites or continuing to provide personal information to us after a notice of changes has been sent to you or published on our Websites shall constitute consent to the changed terms and practices. If you disagree with any changes to this Privacy Policy, you will need to stop using our products, services and/or Websites and deactivate your account(s).

# Children

Children are not eligible to use our Websites and we ask that minors (under the age of 18) do not submit any personal information to us or use our Websites. Our Websites are not directed to children under 18 years of age. We do not knowingly collect personally identifiable information from children under 13. If a parent or guardian becomes aware that his or her child has provided us with Personal Information without their consent, he or she should contact us at privacy@dataatomic.com. If we become aware that a child under 13 has provided us with Personal Information, we will delete such information from our files.

# Contact Us

If you have any questions about this Privacy Policy or our treatment of the information you provide us, please write to us by email at privacy@dataatomic.com.  


# Information We Collect

## Personal Information. 

By using our Websites or purchasing products or services from us, you voluntarily and willingly provide us with certain information, including Personal Information, which we collect in order to provide the Websites and/or the products or services you may order. Personal Information refers to information about you that can be used to contact or identify you, and information on your use of and activities at our Websites that may be connected with you. Personal Information that we collect may include, but is not limited to, your email address and location information. Personal Information may also include information you supply to us concerning your preferences and interests expressed in the course of use of our Websites and products or services. From time to time in the future, we may offer additional products, features, services and promotional opportunities that would require you to submit Personal Information to us in order to participate. If you are unsure whether you would like to provide information to us and/or having your information used as permitted in this Privacy Policy, you should not use our Websites or otherwise provide this information to us.

## Account and Profile Information. 

We collect information about you and your company as you register for an account, create or modify your profile, make purchases through, use, access, or interact with our Websites and/or our products and services (including but not limited to when you upload, download, collaborate on or share Content). If you are providing information (including Personal Information) about someone else, you confirm that you have the authority to act for them and to consent to the collection and use of their Personal Information as described in this Privacy Policy.

## Content. 

We collect and store Content that you create, input, submit, post, upload, transmit, store or display in the process of using our products, services or Websites. Such Content includes any Personal Information or other sensitive information that you choose to include (“passively-collected Personal Information”).

## Navigational Information.

We also collect “Navigational Information” such as your IP address as well as browser type, internet service provider, URLs of referring/exit pages, operating system, date/time stamp, information you search for, locale and language preferences, identification numbers associated with your devices, your mobile carrier, and system configuration information. Some Navigational Information may be associated with Personal Information.

## Analytics Information. 

We and our analytics provider collect and store analytics information when you use our Websites and/or our products and services to help us improve our Websites, products and services. This analytics information consists of web browsing behavior collected through a combination of HTTP beacons and cookies. Analytics information also consists of data we collect as a result of running queries against Content across our user base for the purposes of generating Usage Data. “Usage Data” is aggregated data about a group or category of services, features or users that does not contain Personal Information. Though we may happen upon sensitive or Personal Information as we compile Usage Data from Content across user instances, this is a byproduct of our efforts to understand broader patterns and trends. It is not a concerted effort by us to examine the Content of any particular customer. Some of our products contain a feature that sends information about the version of the products on your systems (“System Information”) to us. System Information includes information about (i) the server environment in which the product is operating: OS type and version, language and locale settings; (ii) user client information, for example: browser type and version, native client type and version, and client device specifications (e.g. screen resolution, OS version, device type, etc.). You can disable our collection of analytics information from products via the administrator settings or by blocking collection at the local network level.

As of the date this policy went into effect, we use Google Analytics as an analytics provider. To learn more about the privacy policy of Google Analytics, refer to Google’s Policies and Principles. Use the Google Analytics Opt-out Browser Add-on to prevent to analytics information from being sent to Google Analytics. We also may use Marketo’s tool to help us with our automated marketing efforts, please refer to http://www.marketo.com/trust/legal/privacy to read about Marketo’s privacy policy.

# How We Collect Information

We collect your information in the following ways:

## Log Files. 

We may collect anonymous demographic information, which is not unique to you, such as your ZIP code, age, gender, preferences, interests and favorites using log files, when you use our Websites and/or our products and services. There is also information about your computer hardware and software that is automatically collected by our Websites. This information may include, but is not limited to, your computer’s Internet Protocol address, browser type, the web page you were visiting before you came to our site, information you search for, domain names, access times and referring website addresses. We may also collect information about the fact that you use certain features and functionality of our service and your responses to our surveys and research initiatives. This information is used by us for the operation of the Websites, to maintain quality of the Websites, and to provide general statistics regarding use of the Website. For these purposes, we do link this automatically-collected data to Personal Information such as name, email address, address, and phone number.

## Cookies. 

Like most websites, we use “cookies” and web log files to collect information to track site usage and trends, to improve our service, and to deliver a customized experience when you use our Websites and/or our products and services. A cookie is a small data file that is placed on your computer, mobile phone or other device by a web server and enables us to recognize you when you return to our site or log into our service. Cookies are uniquely assigned to you, and can only be read by a web server in the domain that issued the cookie to you. One of the primary purposes of cookies is to provide a convenience feature to save you time – for example, when you return to the same website, the information you previously provided can be retrieved, so you can easily use the features that you customized. We may use “persistent cookies” to save your registration ID and login password for future logins to the site. We may also use “session ID cookies”, which expire after a short period of time or when you close your browser. Session ID cookies are used to identify a particular visit and are used to enable certain features of the site or service, to better understand how you interact with the site and service, and to monitor aggregate usage and web traffic routing on the site. We set a cookie and use local storage in your browser that contains information that we use to identify you for the functional site features described below with respect to our current third party vendors Marketo, LinkedIn,  Twitter, YouTube, Zendesk, Google AdWords, Google Tag Manager, and Google Analytics. You have the ability to accept or decline cookies. Most Web browsers automatically accept cookies, but you can usually modify your browser setting to decline cookies if you prefer. If you choose to decline cookies, you may not be able to fully experience the interactive features of the Websites. We keep track of the pages you visit on the Websites, in order to determine what parts of our store and the Websites are the most popular. This data is used to deliver customized content and advertising on the Websites to visitors whose behavior indicates that they are interested in a particular subject area.

### During Installation of Our Products. 

During installation, our software products and services may ask you to “opt-in” to the collection of diagnostic information regarding your use of our software or hardware in order to help our engineers improve our products or services. If you opt in, you agree that we may collect, maintain, and use information about the operation of our products and services.

### While Browsing our Website. 

We use vendors that may collect Personal Information on our behalf. Please see the list of vendors that we currently use and how they may access and use your data, including links to their respective privacy policies at the end of this Privacy Policy.

### Service Providers. 

We monitor the activity on our Website using common software tools and third party service providers. We collect and track information on use of the Website including referral sources, search terms, network information, IP addresses, computer and browser types, and content viewed. Unless combined with Personal Information, this other data does not personally identify any user of the Website. We may also use third party service providers to collect and track statistical information regarding the use of the Website, and to prevent our servers from being abused.

# How We Use Information We Collect

We use the information we collect only in compliance with this Privacy Policy.

### Consent to Use of Your Information. 

By submitting information, including Personal Information, to us, you are expressly and voluntarily accepting the terms and conditions of this Privacy Policy. You have the right to withdraw your consent to our collection and use of your information, but your withdrawal of consent will not be retroactive. We post customer testimonials and comments on our Websites, which may contain Personal Information. We obtain each customer’s consent via email prior to posting the customer’s name and testimonial.

# General. 

We use the information we collect about you (including Personal Information to the extent applicable) for a variety of purposes, including to:

Provide, operate, maintain, improve, and promote our products and services;
Enable you to access and use our products and services;
Process and complete transactions, and send you related information, including purchase confirmations and invoices;
Communicate with you, including responding to your comments, questions, and requests; providing customer service and support; providing you with information about services, features, surveys, newsletters, offers, promotions, contests and events; providing other news or information about us and our select partners; and sending you technical notices, updates, security alerts, and support and administrative messages. Generally, you have the ability to opt out of receiving any promotional communications as described below;
Monitor and analyze trends, usage, and activities in connection with our products and services and for marketing or advertising purposes;
Investigate and prevent fraudulent transactions, unauthorized access to our products and services, and other illegal activities;

For other purposes about which we notify you.

Use of Personal Information. We may use your Personal Information and other information you provide us to (i) provide our Websites and our products and services to you and administer your use of our Websites and our products and services, (ii) to provide you with products or services that you purchase from our online store, (iii) to communicate with you and fulfill requests you may make, including requests for technical support, (iv) to provide you with information and announcements with respect to our products or services, (v) to provide you with further information and offers from us or carefully selected third parties that we believe you may find useful or interesting, including newsletters, marketing or promotional materials and other information on services and products offered by us or third parties, and (iv) provide other companies with statistical information about our users – but this information will not be used to identify any individual user. We may also use the information provided by you or obtained through your use of our Websites or our products or services to improve our products, services and Websites, and improve your browsing experience by personalizing the Websites.

# Use of Navigational Information. 

We use Navigational Information to operate and improve the Websites. We may also use Navigational Information alone or in combination with Personal Information to provide you with personalized information about us and our products and services. We use Navigational Information we obtain by technical means (such as the automatic recording performed by our servers or through the use of cookies) for the above purposes as well as to monitor, measure and analyze use of the Websites and our products and services, and to generate and derive useful data and information concerning the interests, characteristics and use behavior of our customers and visitors to our Websites and their use of our products and services.

# Use of Credit Card Information.

If you give us credit card information, we use it solely to check your financial qualifications and collect payment from you. We use a third-party service provider to manage credit card processing. This service provider is not permitted to store, retain, or use information you provide except for the sole purpose of credit card processing on our behalf.

# Sharing of Your Personal Information

We Never Sell Personal Information. We will never sell, rent or otherwise provide your Personal Information to any third party for marketing purposes.

# Sharing Information with Third Parties. 

We only share your Personal Information with third parties as described in this Privacy Policy, to carry out your instructions, as may be compelled by law, or as necessary to protect our rights or property. For example, we may share data with trusted partners to help us process information, extend credit, fulfill orders for our products and services, sell or deliver products and services to you, provide customer service, assess your interest in products and services, conduct customer research or satisfaction surveys, or help us perform statistical analysis. Such third parties are prohibited from using your Personal Information except for these purposes, and they are required to maintain the confidentiality of your information. We also employ other companies and people to provide services to visitors to our Websites on our behalf and may need to share your information with them to provide information, products or services to you. Examples may include removing repetitive information from prospect lists, analyzing data, providing marketing assistance, processing credit card payments, and providing customer service. In all cases where we share your information with such agents, we explicitly require the agent to acknowledge and adhere to our privacy and customer data handling policies. Dataatomic may be liable if third parties fail to meet Privacy Shield obligations unless we prove we are not responsible for the event giving rise to the damage.

# Community. 

Our Websites offer publicly accessible community services such as blogs and posts. You should be aware that any information or content you provide in these areas may be made public and read, collected, and used by others who access them. Your posts may remain even after you cancel your account.

# Compliance with Legal Process.

We may be required to disclose your Personal Information and/or information with respect to your use of our Websites, products and services in response to lawful requests by governmental or regulatory agency or by court order, subpoena or other legal process or requirement, including to meet national security or law enforcement requirements, or if we reasonably believe that such disclosure is necessary (i) to investigate, prevent or take action with respect to suspected or actual illegal activities or to assist government enforcement agencies, (ii) to protect the safety of any person from death or serious bodily injury, (iii) to prevent fraud or abuse of our Websites, products and services or infringement of our intellectual property rights in our Websites, products and services, (iv) to enforce our terms of use or your agreements with us, or (v) to investigate and defend ourselves against any third party claims or allegations.

# Business Transfers. 

We may sell, transfer or otherwise share your information to a third party in connection with a merger, acquisition, reorganization or sale of assets of Dataatomic or in the event of bankruptcy of Dataatomic and you agree that any such third party will have the right to continue to use your Personal Information and other information that you provide to us or which we obtain through your use of the service.

Aggregated or Anonymized Data. We may also share aggregated or anonymized information that does not directly identify you with the third parties described above.

With Your Consent. We will share your personal information with third parties when we have your consent to do so.

# Accessing Your Information. 

You may access, review, revise, correct, or delete the Personal Information provided in your registration or account profile by changing your “account settings.” If you update any of your information, we may keep a copy of the information that you originally provided to us in our archives for uses documented in this Privacy Policy.

# Security and Retention of Your Personal Information

We use a variety of security technologies and procedures to help protect your Personal Information from unauthorized access, use or disclosure. When sensitive Personal Information (such as a credit card information) is collected on our store, it is protected by our third-party credit card processor. Although we use industry standard security measures, the Internet is not a 100% secure environment and we cannot, and do not, ensure or warrant the security of any information you transmit or store using the Websites. There is no guarantee that your information may not be accessed, disclosed, altered or destroyed by breach of any of our physical, technical or managerial safeguards and we are not responsible for third party circumvention of your privacy settings or our security measures. You are responsible for maintaining the secrecy of your unique password and account information and for controlling access to your account.

We retain Personal Information that you provide us as long as we consider it potentially useful in contacting you about our company, products or services. We retain information about our customers for as long as we need it to provide service to the customer. We will delete this information from our servers at an earlier date if you so request, as described in “Opting-Out and Unsubscribing” below.

If you have submitted a valid GDPR data subject access request to exercise your right to be forgotten we will delete your personal data within 30 days of the request.

If you are an individual based in the EU you can request a copy of your personal data and you can update any incorrect information.

If you are an individual based in the EU, you can ask to have your personal data removed, or in some cases limit our processing of personal data. This does not apply when we need to keep your personal data for legal reasons.

# External Websites

Our Websites provide links to other websites. We do not control, and are not responsible for, the content or practices of these other websites. Our provision of such links does not constitute our endorsement of these other websites, their content, their owners, or their practices. This Privacy Policy does not apply to these other websites, which are subject to any privacy and other policies they may have. You should use caution and review the privacy policies of any web sites, services or third party providers that you visit from our Websites or our products to learn more about their information practices, which may be significantly different from ours.

# Public Forums

We may offer publicly accessible message boards, blogs, and community forums. Please keep in mind that if you directly disclose any information through our public message boards, blogs, or forums, this information may be made public and may be collected and used by others. We will correct or delete any information you have posted on our servers if you so request, as described in “Opting-Out and Unsubscribing” below.

Compliance with privacy laws and regulations
Dataatomic is subject to the investigatory and enforcement powers of the Federal Trade Commission (FTC). You agree not to use our Websites, products or services in a manner that would violate laws protecting an individual’s privacy rights, health or financial data, including the Health Insurance Portability and Accountability Act of 1996 as amended (HIPAA) and the Gramm-Leach-Bliley Act and its implementing regulations, the Privacy Rule and the Safeguards Rule.

## Your Rights as an Individual Based in the EU

In compliance with the Privacy Shield Principles, Dataatomic commits to resolve complaints about our collection or use of your personal information. EU individuals with inquiries or complaints regarding our Privacy Shield policy should first contact Dataatomic at: privacy@dataatomic.com.

Access to your information: You have the right to request a copy of the personal data we hold about you.

Correcting your information: We want to have accurate data. Please contact us if you think the personal data you provided to us is not up to date or correct.

Deletion of your information: You have the right to ask us to delete personal data about you if it no longer is required for the purpose it was collected, you have withdrawn your consent, you have a valid objection to us using your personal data, or our use of your personal data is contrary to law or our other legal obligations.

Objecting to how we may use your information: You have the right at any time to require us to stop using your personal data for direct marketing purposes. In addition, where we use your personal data to perform tasks carried out in the public interest then, if you ask us to, we will stop using that personal data unless there are overriding legitimate grounds to continue.

Restricting how we may use your information: In some cases, you may ask us to restrict how we use your personal data. This right might apply, for example, where we are checking the accuracy of personal data about you that we hold or assessing the validity of any objection you have made to our use of your personal data. The right might also apply where this is no longer a basis for using your personal data but you don’t want us to delete the data. Where this right is validly exercised, we may only use the relevant personal data with your consent, for legal claims or where there are other public interest grounds to do so.

Automated processing: If we use your personal data on an automated basis to make decisions which significantly affect you, you have the right to ask that the decision be reviewed by an individual to whom you may make representations and contest the decision. This right only applies where we use your personal data with your consent or as part of a contractual relationship with you.

Withdrawing consent using your information: Where we use your personal data with your consent you may withdraw that consent at any time and we will stop using your personal data for the purpose(s) for which consent was given.

Please contact if you wish to exercise any of these rights. You can find the contact details below under “Opting-Out and Unsubscribing”.

To review the user information that you have supplied to us
To request that we correct any errors, outdated information, or omissions in user information that you have supplied to us
To request that your user information not be used to contact you
To request that your user information be removed from any solicitation list that we use
To request that your user information be deleted from our records
To otherwise opt out of receiving solicitations
To exercise any of these rights, please contact us at privacy@dataatomic.com.

We will promptly change, correct, or delete your information.

To Unsubscribe From Our Communications. You may unsubscribe from our marketing communications by clicking on the “unsubscribe” link located on the bottom of our emails or by sending us email us at privacy@dataatomic.com

How You Can Opt Out of Web Tracking. There are several ways to opt out of web tracking:

Most browsers allow you to block third-party cookies or prevent cross-domain tracking. This will limit the cookies that can be set by third-party scripts. This will not completely eliminate tracking by some third-party services though as they may use first-party cookies.

Most browsers also allow you ask not to be tracked (it sends the “Do Not Track” request header). If you have enabled this feature, we will not track the pages you visit in a way that enables us to connect them to your personal information. Your page views may still be collected anonymously though. Many of the third-party services we use for collecting anonymous data also respect the Do Not Track setting.


# Third Party Vendors. 

Some of the vendors we use that may collect Personal Information on our behalf are as follows:

LinkedIn: We use LinkedIn in conjunction with metadata.io to reach target audiences via LinkedIn Ads and their inbox. Read LinkedIn’s privacy policy here. https://www.linkedin.com/legal/preview/privacy-policy

Google Analytics: We use Google Analytics to review data on website visits including: geographical information, browser information, platform information, page information, visit duration, referring site, time of visits, click throughs. The data is used to improve our site. Read the Google Analytics privacy policy here. https://policies.google.com/privacy?hl=en

Google Tag Manager: We use Google Tag Manager to manage and deploy marketing tags (snippets of code or tracking pixels) on our website. Read Google Tag Manager’s privacy policy here. https://www.google.com/analytics/tag-manager/use-policy/

YouTube: We use YouTube as a host to reach more people with our video content. Read YouTube’s privacy policy here. https://www.youtube.com/static?template=privacy_guidelines

Marketo: We use Marketo to manage registrations on our websites, to collect and store consent, and to send consent-based email communications. We also use Marketo to track web visits if you have registered on our website. Read Marketo’s privacy policy here.

Twitter: We use Twitter on our websites to enable Twitter’s audience to share our content and follow our Twitter accounts. Read Twitter’s privacy policy here.

