---
title: "terms_and_conditions"
author: "Dataatomic"
date: "4/20/2020"
output: html_document
---

1. Acceptance of Terms and Conditions of Use.

These Website Terms and Conditions of Use (the “Terms of Use”) apply to the Dataatomic,  web site located at www.dataatomic.com and all associated sites linked to www.dataatomic.com by Dataatomic, its subsidiaries and affiliates (collectively, the “Site”). The Site is the property of Dataatomic. BY USING THE SITE, YOU AGREE TO THESE TERMS OF USE; IF YOU DO NOT AGREE, DO NOT USE THE SITE.

Dataatomic reserves the right, at its sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time. It is your responsibility to check these Terms of Use periodically for changes. Your continued use of the Site following the posting of changes will mean that you accept and agree to the changes. 

2. Content.

All text, graphics, user interfaces, visual interfaces, photographs, trademarks, logos, sounds, music, artwork and computer code (collectively, “Content”), including but not limited to the design, structure, selection, coordination, expression, “look and feel” and arrangement of such Content, contained on the Site is owned, controlled or licensed by or to Dataatomic, and is protected by trade dress, copyright, patent and trademark laws, and various other intellectual property rights and unfair competition laws.

Except as expressly provided in these Terms of Use, no part of the Site and no Content may be copied, reproduced, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted or distributed in any way (including “mirroring”) to any other computer, server, Web site or other medium for publication or distribution or for any commercial enterprise, without Dataatomic’s express prior written consent.

You may use information on Dataatomic products and services purposely made available by Dataatomic for downloading from the Site, provided that you (1) not remove any proprietary notice language in all copies of such documents, (2) use such information only for your personal, non-commercial informational purpose and do not copy or post such information on any networked computer or broadcast it in any media, (3) make no modifications to any such information, and (4) not make any additional representations or warranties relating to such documents.


3. Purchases; Other Terms and Conditions

Additional terms and conditions may apply to purchases of goods or services, downloads of software, and to specific portions or features of the Site, including community forums, contests, promotions or other similar features, all of which terms are made a part of these Terms of Use by this reference, such as and including without limitation EULA,  Dataatomic Service Terms of Use, Individual Contributor Agreement , Corporate Contributor Agreement, Connect Beta Terms of Use  among others.

You agree to abide by such other terms and conditions, including where applicable representing that you are of sufficient legal age to purchase, use or participate in such service or feature. If there is a conflict between these Terms of Use and the terms posted for or applicable to a specific portion of the Site or for any service offered on or through the Site, the latter terms shall control with respect to your use of that portion of the Site or the specific service.

Dataatomic's obligations, if any, with regard to its products and services are governed solely by the agreements pursuant to which they are provided, and nothing on this Site should be construed to alter such agreements.

Dataatomic may make changes to any products or services offered on the Site, or to the applicable prices for any such products or services, at any time, without notice. The materials on the Site with respect to products and services may be out of date, and Dataatomic makes no commitment to update the materials on the Site with respect to such products and services.

To the extent Dataatomic makes available third party applications, products, software, services, data, content or resources or other third party goods or services on the Site or links to third party websites, Dataatomic does so for your convenience and makes no representations or warranties with respect to any of the foregoing, all of which is provided “as is” and without warranty.  Dataatomic disclaims all liability arising from your download or use of the foregoing. Such third party materials may be subject to additional terms and conditions and licenses between you and the third party. YOU AGREE THAT IN NO EVENT WILL WE BE LIABLE TO YOU IN CONNECTION WITH THE WEBSITES, CONTENT, APPLICATIONS, PACKAGES, COMPONENTS, SERVICES, DATA, CONTENT, RESOURCES, MATERIALS OR PRACTICES OF ANY THIRD PARTY.

4. Communications.

Except for any disclosure by you for technical support purposes, or as specified in our Privacy Policy, all communications from you to Dataatomic will be considered non-confidential and non-proprietary. You agree that any and all comments, information, feedback and ideas regarding Dataatomic, its products or services, that you communicate to Dataatomic (“Feedback”) will be deemed, at the time of communication to Dataatomic, the property of Dataatomic, and Dataatomic shall be entitled to full rights of ownership, including without limitation, unrestricted right to use or disclose such Feedback in any form, medium or technology now known or later developed, and for any purpose, commercial or otherwise, without compensation to you.

You are solely responsible for the content of your communications and their legality under all laws and regulations. You agree not to use this Site to distribute, link to or solicit content that is defamatory, harassing, unlawful, libelous, harmful to minors, threatening, obscene, false, misleading, or infringing a third party intellectual or privacy rights.

5. Access to Password Protected or Secured Areas; Privacy.

Access to and use of password protected or secured areas of this Site is restricted to authorized users only and certain features or services offered on or through the Site may require you to open an account (including setting up an Dataatomic ID and password). You are entirely responsible for maintaining the confidentiality of your account information, including your password, and for any and all activity that occurs under your account. You agree to notify Dataatomic immediately of any unauthorized use of your account or password, or any other breach of security. However, you may be held liable for losses incurred by Dataatomic or any other user of or visitor to the Site due to someone else using your Dataatomic ID, password or account. You will not misuse or share your username or password, misrepresent your identity or your affiliation with an entity, impersonate any person or entity, or misstate the origin of any Content you are exposed to through this Site.

Dataatomic’s Privacy Policy applies to use of this Site, and its terms are made a part of these Terms of Use by this reference. Additionally, by using the Site, you acknowledge and agree that Internet transmissions are never completely private or secure. You understand that any message or information you send to the Site may be read or intercepted by others, even if there is a special notice that a particular transmission (for example, credit card information) is encrypted.

6. Monitoring.

Dataatomic reserves the right to review your communications on this Site to determine whether you comply with these Terms of Use and any other applicable polices or terms and conditions of Dataatomic applicable to your use of the Site. Dataatomic will not have any liability or responsibility for the content of any communications you post to this Site, or for any errors or violations of any laws or regulations by you. Dataatomic will comply with any court order in disclosing the identity of any person posting communications on this Site. It is advisable that you review our Privacy Statement before posting any such communications.

7. Links to Other Sites.

This Site may link to other third party sites which are not under the control of Dataatomic. Dataatomic is not responsible for the content of any linked site or any link contained in a linked site. Dataatomic reserves the right to terminate any link at any time. Dataatomic may provide links from this Site to other sites as a convenience to you and in no way should this be interpreted as an endorsement of any company, content or products to which it links. If you decide to access any of the third party sites linked to this Site, you do this entirely at your own risk. Please note that when you conduct transactions with other companies providing content via this Site, you will also be subject to their privacy policies.  Dataatomic DISCLAIMS ANY AND ALL WARRANTIES, EXPRESS OR IMPLIED, TO ANY SUCH LINKED SITES, INCLUDING BUT NOT LIMITED TO ANY TERMS AS TO THE ACCURACY, OWNERSHIP, VALIDITY OR LEGALITY OF ANY CONTENT OF A LINKED SITE.

8. Trademarks.

The trademarks, service marks and logos of Dataatomic used through the Site (“Trademarks”) are the property of Dataatomic. You have no right to use any such Trademarks, and nothing contained in this Site or the Terms of Use grants any right to use (by implication, waiver, estoppel or otherwise) any Trademarks without the prior written permission of Dataatomic.

9. Indemnification.

You agree to indemnify, defend and hold Dataatomic, its officers, directors, shareholders, predecessors, successors in interest, employees, agents, subsidiaries and affiliates, harmless from and against any demands, loss, liability, claims or expenses (including attorneys’ fees) arising out of, based on or in connection with your access and/or use of this Site

10. Limitation of Liability.

EXCEPT WHERE PROHIBITED BY LAW, IN NO EVENT WILL DATAATOMIC BE LIABLE TO YOU FOR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL OR PUNITIVE DAMAGES, INCLUDING LOST PROFITS, EVEN IF DATAATOMIC HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

IF, NOTWITHSTANDING THE OTHER PROVISIONS OF THESE TERMS OF USE, DATAATOMIC IS FOUND TO BE LIABLE TO YOU FOR ANY DAMAGE OR LOSS WHICH ARISES OUT OF OR IS IN ANY WAY CONNECTED WITH YOUR USE OF THE SITE OR ANY CONTENT, DATAATOMIC’S LIABILITY SHALL IN NO EVENT EXCEED THE GREATER OF (1) THE TOTAL OF ANY SUBSCRIPTION OR SIMILAR FEES WITH RESPECT TO ANY SERVICE OR FEATURE OF OR ON THE SITE PAID IN THE SIX MONTHS PRIOR TO THE DATE OF THE INITIAL CLAIM MADE AGAINST DATAATOMIC, OR (2) US$100.00. SOME JURISDICTIONS DO NOT ALLOW LIMITATIONS OF LIABILITY, SO THE FOREGOING LIMITATION MAY NOT APPLY TO YOU.

11. Disclaimer.

DATAATOMIC DOES NOT PROMISE THAT THE SITE OR ANY CONTENT, SERVICE OR FEATURE OF THE SITE WILL BE ERROR-FREE OR UNINTERRUPTED, OR THAT ANY DEFECTS WILL BE CORRECTED, OR THAT YOUR USE OF THE SITE WILL PROVIDE SPECIFIC RESULTS. THE SITE AND ITS CONTENT ARE DELIVERED ON AN “AS-IS” AND “AS-AVAILABLE” BASIS. ALL INFORMATION PROVIDED ON THE SITE IS SUBJECT TO CHANGE WITHOUT NOTICE. DATAATOMIC CANNOT ENSURE THAT ANY FILES OR OTHER DATA YOU DOWNLOAD FROM THE SITE WILL BE FREE OF VIRUSES OR CONTAMINATION OR DESTRUCTIVE FEATURES. DATAATOMIC DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING ANY WARRANTIES OF ACCURACY, NON-INFRINGEMENT, MERCHANTABILITY, TITLE AND FITNESS FOR A PARTICULAR PURPOSE. DATAATOMIC DISCLAIMS ANY AND ALL LIABILITY FOR THE ACTS, OMISSIONS AND CONDUCT OF ANY THIRD PARTIES IN CONNECTION WITH OR RELATED TO YOUR USE OF THE SITE AND/OR ANY DATAATOMIC SERVICES. YOU ASSUME TOTAL RESPONSIBILITY FOR YOUR USE OF THE SITE AND ANY LINKED SITES. YOUR SOLE REMEDY AGAINST DATAATOMIC FOR DISSATISFACTION WITH THE SITE OR ANY CONTENT IS TO STOP USING THE SITE OR ANY SUCH CONTENT. THIS LIMITATION OF RELIEF IS AN ESSENTIAL PART OF THE BARGAIN BETWEEN THE PARTIES.

The above disclaimer applies to any damages, liability or injuries caused by any failure of performance, error, omission, interruption, deletion, defect, delay in operation or transmission, computer virus, communication line failure, theft or destruction of or unauthorized access to, alteration of, or use, whether for breach of contract, tort, negligence or any other cause of action.

Dataatomic reserves the right to do any of the following, at any time, without notice: (1) to modify, suspend or terminate operation of or access to the Site, or any portion of the Site, for any reason; (2) to modify or change the Site, or any portion of the Site, and any applicable policies or terms; and (3) to interrupt the operation of the Site, or any portion of the Site, as necessary to perform routine or non-routine maintenance, error correction, or other changes.

12. Violations of these Terms of Use

Dataatomic may disclose any information we have about you (including your identity) if we determine that such disclosure is necessary in connection with any investigation or complaint regarding your use of the Site, or to identify, contact or bring legal action against someone who may be causing injury to or interference with (either intentionally or unintentionally) Dataatomic’s rights or property, or the rights or property of visitors to or users of the Site, including Dataatomic customers. Dataatomic reserves the right at all times to disclose any information that Dataatomic deems necessary to comply with any applicable law, regulation, legal process or governmental request. Dataatomic also may disclose your information when Dataatomic determines that applicable law requires or permits such disclosure, including exchanging information with other companies and organizations for fraud protection purposes.

You acknowledge and agree that Dataatomic may preserve any transmittal or communication by you with Dataatomic through the Site or any service offered on or through the Site, and may also disclose such data if required to do so by law or Dataatomic determines that such preservation or disclosure is reasonably necessary to (1) comply with legal process, (2) enforce these Terms of Use, (3) respond to claims that any such data violates the rights of others, or (4) protect the rights, property or personal safety of Dataatomic, its employees, users of or visitors to the Site, and the public.

You agree that Dataatomic may, in its sole discretion and without prior notice, terminate your access to the Site and/or block your future access to the Site if we determine that you have violated these Terms of Use or other agreements or guidelines which may be associated with your use of the Site. You also agree that any violation by you of these Terms of Use will constitute an unlawful and unfair business practice, and will cause irreparable harm to Dataatomic, for which monetary damages would be inadequate, and you consent to Dataatomic obtaining any injunctive or equitable relief that Dataatomic deems necessary or appropriate in such circumstances. These remedies are in addition to any other remedies Dataatomic may have at law or in equity.

You agree that Dataatomic may, in its sole discretion and without prior notice, terminate your access to the Site, for cause, which includes (but is not limited to) (1) requests by law enforcement or other government agencies, (2) a request by you (self-initiated account deletions), (3) discontinuance or material modification of the Site or any service offered on or through the Site, or (4) unexpected technical issues or problems.

If Dataatomic does take any legal action against you as a result of your violation of these Terms of Use, Dataatomic will be entitled to recover from you, and you agree to pay, all reasonable attorneys’ fees and costs of such action, in addition to any other relief granted to Dataatomic. You agree that Dataatomic will not be liable to you or to any third party for termination of your access to the Site as a result of any violation of these Terms of Use.


13. Applicable Laws.

All matters relating to your access and use of Site shall be governed by the federal laws of the United States and the laws of The Commonwealth of Massachusetts, without regard to its conflicts of laws provisions. You agree to the personal jurisdiction and venue in the federal and state courts located in Boston, Massachusetts, and waive any objection to such jurisdiction or venue. Any claim under these Terms of Use must be brought within one (1) year after the cause of action arises, or such claim or cause of action is barred. No recovery may be sought or received for damages other than out-of-pocket expenses, except that the prevailing party will be entitled to costs and attorneys’ fees. In the event of any controversy or dispute between Dataatomic and you arising out of or in connection with your use of the Site, the parties shall attempt, promptly and in good faith, to resolve any such dispute. If we are unable to resolve any such dispute within a reasonable time (not to exceed thirty (30) days), then either party may submit such controversy or dispute to mediation. If the dispute cannot be resolved through mediation, then the parties shall be free to pursue any right or remedy available to them under applicable law.

14. General.

Although the Site is accessible worldwide, not all features, products or services discussed, referenced, provided or offered through or on the Site are available to all persons or in all geographic locations, or appropriate or available for use outside the United States. Dataatomic reserves the right to limit, in its sole discretion, the provision and quantity of any feature, product or service to any person or geographic area. Any offer for any feature, product or service made on the Site is void where prohibited. If you choose to access the Site from outside the United States, you do so on your own initiative and you are solely responsible for complying with applicable local laws.

If any of the provisions of these Terms of Use are held by a court or other tribunal of competent jurisdiction to be void or unenforceable, such provisions shall be limited or eliminated to the minimum extent necessary and replaced with a valid provision that best embodies the intent of these Terms of Use, so that these Terms of Use shall remain in full force and effect. These Terms of Use and any other applicable Dataatomic policies and terms and conditions applicable to you constitute the entire agreement between you and Dataatomic with regard to your use of the Site, and any and all other written or oral agreements or understandings previously existing between you and Dataatomic with respect to such use are hereby superseded and cancelled. Dataatomic will not accept any counter-offers to these Terms of Use, and all such offers are hereby categorically rejected. Dataatomic’s failure to insist on or enforce strict performance of these Terms of Use shall not be construed as a waiver by Dataatomic of any provision or any right it has to enforce these Terms of Use, nor shall any course of conduct between Dataatomic and you or any other party be deemed to modify any provision of these Terms of Use. These Terms of Use shall not be interpreted or construed to confer any rights or remedies on any third parties.

If you have any questions regarding the Terms of Use, please contact us at privacy@Dataatomic.com.  