<!DOCTYPE html>
<html lang="en-us">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Source Themes Academic 4.5.0">

  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Serdar Korur">

  
  
  
    
  
  <meta name="description" content="Would you be taking care of yourself better if your doctor told today that you have high risk of diabetes?
Technological advances in fields, such as omics and internet of things (sensors that collect data), and centralization of healthcare information (e.g. OMOP common data model) enable us to access much wider data sources.
Gaining insights from those we can improve our well being with better healthcare. Some applications of machine learning tools are;">

  
  <link rel="alternate" hreflang="en-us" href="/2019/10/01/predict-diseases/">

  


  
  
  
  <meta name="theme-color" content="#2962ff">
  

  
  
  
  
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css" integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.0/css/all.css" integrity="sha384-aOkxzJ5uQz7WBObEZcHvV5JvRW3TUc2rNPA7pe3AwnsUohiw1Vj2Rgx2KSOkF5+h" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.css" integrity="sha256-ygkqlh3CYSUri3LhQxzdcm0n1EQvH2Y+U5S2idbLtxs=" crossorigin="anonymous">

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/styles/github.min.css" crossorigin="anonymous" title="hl-light">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/styles/dracula.min.css" crossorigin="anonymous" title="hl-dark" disabled>
        
      
    

    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.2.0/leaflet.css" integrity="sha512-M2wvCLH6DSRazYeZRIm1JnYyh22purTM+FDB5CsyxtQJYeKq83arPe5wgbNmcFXGqiSH2XR8dT/fJISVA1r/zQ==" crossorigin="anonymous">
    

    

  

  
  
  
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700%7CRoboto:400,400italic,700%7CRoboto+Mono&display=swap">
  

  
  
  
  <link rel="stylesheet" href="/css/academic.min.54abc5f3f1ddc380a34d4103fd11d77a.css">

  

  
  
    <script>
      window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
      ga('create', 'UA-148414815-1', 'auto');
      
      ga('require', 'eventTracker');
      ga('require', 'outboundLinkTracker');
      ga('require', 'urlChangeTracker');
      ga('send', 'pageview');
    </script>
    <script async src="https://www.google-analytics.com/analytics.js"></script>
    
    <script async src="https://cdnjs.cloudflare.com/ajax/libs/autotrack/2.4.1/autotrack.js" integrity="sha512-HUmooslVKj4m6OBu0OgzjXXr+QuFYy/k7eLI5jdeEy/F4RSgMn6XRWRGkFi5IFaFgy7uFTkegp3Z0XnJf3Jq+g==" crossorigin="anonymous"></script>
    
  
  

  

  <link rel="manifest" href="/index.webmanifest">
  <link rel="icon" type="image/png" href="/img/icon-32.png">
  <link rel="apple-touch-icon" type="image/png" href="/img/icon-192.png">

  <link rel="canonical" href="/2019/10/01/predict-diseases/">

  
  
  
  
    
    
  
  
  <meta property="twitter:card" content="summary">
  
  <meta property="og:site_name" content="SERDAR KORUR">
  <meta property="og:url" content="/2019/10/01/predict-diseases/">
  <meta property="og:title" content="Can machine learning change your life style? | SERDAR KORUR">
  <meta property="og:description" content="Would you be taking care of yourself better if your doctor told today that you have high risk of diabetes?
Technological advances in fields, such as omics and internet of things (sensors that collect data), and centralization of healthcare information (e.g. OMOP common data model) enable us to access much wider data sources.
Gaining insights from those we can improve our well being with better healthcare. Some applications of machine learning tools are;"><meta property="og:image" content="/img/logo.png">
  <meta property="twitter:image" content="/img/logo.png"><meta property="og:locale" content="en-us">
  
    
      <meta property="article:published_time" content="2019-10-01T00:00:00&#43;00:00">
    
    <meta property="article:modified_time" content="2019-10-01T09:09:36&#43;02:00">
  

  


    






  





  





  





<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BlogPosting",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "/2019/10/01/predict-diseases/"
  },
  "headline": "Can machine learning change your life style?",
  
  "datePublished": "2019-10-01T00:00:00Z",
  "dateModified": "2019-10-01T09:09:36+02:00",
  
  "author": {
    "@type": "Person",
    "name": "Serdar Korur"
  },
  
  "publisher": {
    "@type": "Organization",
    "name": "SERDAR KORUR",
    "logo": {
      "@type": "ImageObject",
      "url": "/img/logo.png"
    }
  },
  "description": "Would you be taking care of yourself better if your doctor told today that you have high risk of diabetes?\nTechnological advances in fields, such as omics and internet of things (sensors that collect data), and centralization of healthcare information (e.g. OMOP common data model) enable us to access much wider data sources.\nGaining insights from those we can improve our well being with better healthcare. Some applications of machine learning tools are;"
}
</script>

  

  


  


  





  <title>Can machine learning change your life style? | SERDAR KORUR</title>

</head>

<body id="top" data-spy="scroll" data-offset="70" data-target="#TableOfContents" >

  <aside class="search-results" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Search</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        <input name="q" id="search-query" placeholder="Search..." autocapitalize="off"
        autocomplete="off" autocorrect="off" spellcheck="false" type="search">
        
      </div>

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>


  
<nav class="navbar navbar-light fixed-top navbar-expand-lg py-0 compensate-for-scrollbar" id="navbar-main">
  <div class="container">

    
      <a class="navbar-brand" href="/"><img src="/img/logo.png" alt="SERDAR KORUR"></a>
      
      <button type="button" class="navbar-toggler" data-toggle="collapse"
              data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span><i class="fas fa-bars"></i></span>
      </button>
      

    
    <div class="collapse navbar-collapse" id="navbar">

      
      
      <ul class="navbar-nav mr-auto">
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#about"><span>Home</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#posts"><span>Posts</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#contact"><span></span></a>
        </li>

        
        

      
      </ul>
      <ul class="navbar-nav ml-auto">
      

        

        
        <li class="nav-item">
          <a class="nav-link js-search" href="#"><i class="fas fa-search" aria-hidden="true"></i></a>
        </li>
        

        

        
        <li class="nav-item">
          <a class="nav-link js-dark-toggle" href="#"><i class="fas fa-moon" aria-hidden="true"></i></a>
        </li>
        

      </ul>

    </div>
  </div>
</nav>


  <article class="article">

  












  

  
  
  
<div class="article-container pt-3">
  <h1>Can machine learning change your life style?</h1>

  

  
    



<div class="article-metadata">

  
  

  
  <span class="article-date">
    
    
      
          Last updated on
      
    
    Oct 1, 2019
  </span>
  

  

  
  <span class="middot-divider"></span>
  <span class="article-reading-time">
    13 min read
  </span>
  

  
  
  
  <span class="middot-divider"></span>
  <a href="/2019/10/01/predict-diseases/#disqus_thread"></a>
  

  
  

  
    
<div class="share-box" aria-hidden="true">
  <ul class="share">
    
      
      
      
        
      
      
      
      <li>
        <a href="https://twitter.com/intent/tweet?url=/2019/10/01/predict-diseases/&amp;text=Can%20machine%20learning%20change%20your%20life%20style?" target="_blank" rel="noopener" class="share-btn-twitter">
          <i class="fab fa-twitter"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.facebook.com/sharer.php?u=/2019/10/01/predict-diseases/&amp;t=Can%20machine%20learning%20change%20your%20life%20style?" target="_blank" rel="noopener" class="share-btn-facebook">
          <i class="fab fa-facebook-f"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="mailto:?subject=Can%20machine%20learning%20change%20your%20life%20style?&amp;body=/2019/10/01/predict-diseases/" target="_blank" rel="noopener" class="share-btn-email">
          <i class="fas fa-envelope"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.linkedin.com/shareArticle?url=/2019/10/01/predict-diseases/&amp;title=Can%20machine%20learning%20change%20your%20life%20style?" target="_blank" rel="noopener" class="share-btn-linkedin">
          <i class="fab fa-linkedin-in"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://web.whatsapp.com/send?text=Can%20machine%20learning%20change%20your%20life%20style?%20/2019/10/01/predict-diseases/" target="_blank" rel="noopener" class="share-btn-whatsapp">
          <i class="fab fa-whatsapp"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://service.weibo.com/share/share.php?url=/2019/10/01/predict-diseases/&amp;title=Can%20machine%20learning%20change%20your%20life%20style?" target="_blank" rel="noopener" class="share-btn-weibo">
          <i class="fab fa-weibo"></i>
        </a>
      </li>
    
  </ul>
</div>


  

</div>

    














  
</div>



  <div class="article-container">

    <div class="article-style">
      


<p>Would you be taking care of yourself better if your doctor told today that you have <strong>high risk of diabetes?</strong></p>
<p>Technological advances in fields, such as omics and internet of things (sensors that collect data), and centralization of healthcare information (e.g. <a href="https://www.ohdsi.org/data-standardization/the-common-data-model/">OMOP common data model</a>) enable us to access much wider data sources.</p>
<p>Gaining insights from those we can improve our well being with better healthcare. Some applications of machine learning tools are;</p>
<ul>
<li>Diagnosing diseases earlier</li>
<li>Identifiying drugs with reduced side effects</li>
<li>Select patient groups responding to an experimental therapy</li>
<li>Utilize existing therapies better</li>
</ul>
<p><strong>Let’s look at an example and try to help some doctors in diagnosing their patients.</strong></p>
<div id="problem-formulation" class="section level3">
<h3>Problem formulation</h3>
<blockquote>
<p>Can we build a Machine learning algorithm to predict which patients will develop Diabetes?</p>
</blockquote>
<p>The goal is to predict a Binary <strong>Outcome</strong>: <code>Diabetes</code> vs <code>Healthy</code>
by using 8 medical indicators.</p>
</div>
<div id="overview-of-the-data" class="section level3">
<h3>Overview of the data</h3>
<p><strong>The Pima Indians of Arizona and Mexico</strong> have contributed to numerous scientific gains. Their involvement has led to significant findings on genetics of both <strong>type 2 diabetes</strong> and <strong>obesity.</strong></p>
<p>The medical indicators recorded are;</p>
<p><strong>Pregnancies:</strong> Number of times pregnant<br />
<strong>Glucose:</strong> Plasma glucose concentration a 2 hours in an oral glucose tolerance test<br />
<strong>BloodPressure:</strong> Diastolic blood pressure (mm Hg)<br />
<strong>SkinThickness:</strong> Triceps skin fold thickness (mm)<br />
<strong>Insulin:</strong> 2-Hour serum insulin (mu U/ml)<br />
<strong>BMI:</strong> Body mass index (weight in kg/(height in m)^2)<br />
<strong>DiabetesPedigreeFunction:</strong> Diabetes pedigree function<br />
<strong>Age:</strong> Age (years)<br />
<strong>Outcome:</strong> Class variable (0 or 1)</p>
</div>
<div id="data-acquisition" class="section level3">
<h3>Data acquisition</h3>
<p>I downloaded the <a href="https://www.kaggle.com/uciml/pima-indians-diabetes-database">Pima Indians Diabetes Dataset</a> from Kaggle and imported it from my local directory.</p>
<pre class="r"><code>diabetes &lt;- read.csv(&quot;posts_data/diabetes.csv&quot;)

library(dplyr)
library(reshape2)
library(ggplot2)
library(ggcorrplot)
library(pROC)
library(lattice)
library(caret)</code></pre>
</div>
<div id="data-quality-control" class="section level3">
<h3>Data Quality control</h3>
<p>Before counting on any algorithm a good starting point is to <strong>check obvious mistakes and abnormalities in your data.</strong></p>
<p>Here, I would look at <strong>Missing values</strong>, variable ranges (<strong>min, max values</strong>). A very extreme value might be basically a sign of typing error.</p>
<div id="understand-your-data" class="section level4">
<h4>Understand your Data</h4>
<p>How big is the data? Checking the size and also type of variables.</p>
<pre class="r"><code>dim(diabetes)</code></pre>
<pre><code>## [1] 768   9</code></pre>
<pre class="r"><code>knitr::kable(sapply(diabetes, class))</code></pre>
<table>
<thead>
<tr class="header">
<th></th>
<th align="left">x</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Pregnancies</td>
<td align="left">integer</td>
</tr>
<tr class="even">
<td>Glucose</td>
<td align="left">integer</td>
</tr>
<tr class="odd">
<td>BloodPressure</td>
<td align="left">integer</td>
</tr>
<tr class="even">
<td>SkinThickness</td>
<td align="left">integer</td>
</tr>
<tr class="odd">
<td>Insulin</td>
<td align="left">integer</td>
</tr>
<tr class="even">
<td>BMI</td>
<td align="left">numeric</td>
</tr>
<tr class="odd">
<td>DiabetesPedigreeFunction</td>
<td align="left">numeric</td>
</tr>
<tr class="even">
<td>Age</td>
<td align="left">integer</td>
</tr>
<tr class="odd">
<td>Outcome</td>
<td align="left">integer</td>
</tr>
</tbody>
</table>
<p>Next, what catches my attention is <strong>unexpected zero values in Insulin</strong> below.</p>
<pre class="r"><code>knitr::kable(head(diabetes))</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">Pregnancies</th>
<th align="right">Glucose</th>
<th align="right">BloodPressure</th>
<th align="right">SkinThickness</th>
<th align="right">Insulin</th>
<th align="right">BMI</th>
<th align="right">DiabetesPedigreeFunction</th>
<th align="right">Age</th>
<th align="right">Outcome</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">6</td>
<td align="right">148</td>
<td align="right">72</td>
<td align="right">35</td>
<td align="right">0</td>
<td align="right">33.6</td>
<td align="right">0.627</td>
<td align="right">50</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="right">85</td>
<td align="right">66</td>
<td align="right">29</td>
<td align="right">0</td>
<td align="right">26.6</td>
<td align="right">0.351</td>
<td align="right">31</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">8</td>
<td align="right">183</td>
<td align="right">64</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">23.3</td>
<td align="right">0.672</td>
<td align="right">32</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="right">89</td>
<td align="right">66</td>
<td align="right">23</td>
<td align="right">94</td>
<td align="right">28.1</td>
<td align="right">0.167</td>
<td align="right">21</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">0</td>
<td align="right">137</td>
<td align="right">40</td>
<td align="right">35</td>
<td align="right">168</td>
<td align="right">43.1</td>
<td align="right">2.288</td>
<td align="right">33</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="right">5</td>
<td align="right">116</td>
<td align="right">74</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">25.6</td>
<td align="right">0.201</td>
<td align="right">30</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
</div>
<div id="missing-values" class="section level4">
<h4>Missing Values</h4>
<p>Summary gives a good overview of the variables. Any missing data will show up here listed as <strong>“NA’s”</strong>.</p>
<pre class="r"><code>summary(diabetes)</code></pre>
<pre><code>##   Pregnancies        Glucose      BloodPressure    SkinThickness  
##  Min.   : 0.000   Min.   :  0.0   Min.   :  0.00   Min.   : 0.00  
##  1st Qu.: 1.000   1st Qu.: 99.0   1st Qu.: 62.00   1st Qu.: 0.00  
##  Median : 3.000   Median :117.0   Median : 72.00   Median :23.00  
##  Mean   : 3.845   Mean   :120.9   Mean   : 69.11   Mean   :20.54  
##  3rd Qu.: 6.000   3rd Qu.:140.2   3rd Qu.: 80.00   3rd Qu.:32.00  
##  Max.   :17.000   Max.   :199.0   Max.   :122.00   Max.   :99.00  
##     Insulin           BMI        DiabetesPedigreeFunction      Age       
##  Min.   :  0.0   Min.   : 0.00   Min.   :0.0780           Min.   :21.00  
##  1st Qu.:  0.0   1st Qu.:27.30   1st Qu.:0.2437           1st Qu.:24.00  
##  Median : 30.5   Median :32.00   Median :0.3725           Median :29.00  
##  Mean   : 79.8   Mean   :31.99   Mean   :0.4719           Mean   :33.24  
##  3rd Qu.:127.2   3rd Qu.:36.60   3rd Qu.:0.6262           3rd Qu.:41.00  
##  Max.   :846.0   Max.   :67.10   Max.   :2.4200           Max.   :81.00  
##     Outcome     
##  Min.   :0.000  
##  1st Qu.:0.000  
##  Median :0.000  
##  Mean   :0.349  
##  3rd Qu.:1.000  
##  Max.   :1.000</code></pre>
<p>I will make visualizations of the variables to see how they are distributed.</p>
<pre class="r"><code>gg &lt;- melt(diabetes)</code></pre>
<pre><code>## No id variables; using all as measure variables</code></pre>
<pre class="r"><code>ggplot(gg, aes(x=value, fill=variable)) +
  geom_histogram(binwidth=5)+ 
  facet_wrap(~variable) </code></pre>
<p><img src="/post/2019-10-01-can-machine-learning-change-your-life-style_files/figure-html/Check%20out%20how%20variables%20are%20distributed-1.png" width="672" /></p>
<p>Peaks at zero of Skin Thickness and Insulin is obvious here. Technically it is not possible to have Blood Pressure or Glucose levels at 0.</p>
<p>In cases where the numbers are small we might remove them. Here they seem plenty. <strong>Let’s figure it out with a for loop.</strong></p>
<p>This will bring me the number of zero containing rows in variables from 2 to 6.</p>
<pre class="r"><code>zero_rows &lt;- list()
for(i in 2:6){
zero_rows[[i]] &lt;- length(which(diabetes[,i] == 0))  
}
rows_with_zero &lt;- unlist(zero_rows)
df &lt;- data.frame(rows_with_zero, row.names = names(diabetes[2:6]))
df</code></pre>
<pre><code>##               rows_with_zero
## Glucose                    5
## BloodPressure             35
## SkinThickness            227
## Insulin                  374
## BMI                       11</code></pre>
<p>For instance, in Insulin <strong>374</strong> values are zero. It is unlikely that those are simply entry mistakes. It seems missing values are filled with <strong>zeros</strong> in the data collection phase.</p>
<p><strong>How to circumwent this?</strong></p>
</div>
</div>
<div id="convert-all-zeroes-to-nas-and-then-perform-median-imputation" class="section level2">
<h2>Convert all <strong>zeroes</strong> to <strong>NAs</strong> and then perform <strong>Median Imputation</strong></h2>
<p>I will use a for loop to remove zeros in all the predictors except Pregnancy and Pedigree function.</p>
<pre class="r"><code>for(i in 2:6){
# Convert zeros to NAs
diabetes[, i][diabetes[, i] == 0] &lt;- NA
# Calculate median
median &lt;- median(diabetes[, i], na.rm = TRUE)
diabetes[, i][is.na(diabetes[, i])] &lt;- median
}</code></pre>
<p>Check if it really happened</p>
<pre class="r"><code>knitr::kable(head(diabetes))</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">Pregnancies</th>
<th align="right">Glucose</th>
<th align="right">BloodPressure</th>
<th align="right">SkinThickness</th>
<th align="right">Insulin</th>
<th align="right">BMI</th>
<th align="right">DiabetesPedigreeFunction</th>
<th align="right">Age</th>
<th align="right">Outcome</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">6</td>
<td align="right">148</td>
<td align="right">72</td>
<td align="right">35</td>
<td align="right">125</td>
<td align="right">33.6</td>
<td align="right">0.627</td>
<td align="right">50</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="right">85</td>
<td align="right">66</td>
<td align="right">29</td>
<td align="right">125</td>
<td align="right">26.6</td>
<td align="right">0.351</td>
<td align="right">31</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">8</td>
<td align="right">183</td>
<td align="right">64</td>
<td align="right">29</td>
<td align="right">125</td>
<td align="right">23.3</td>
<td align="right">0.672</td>
<td align="right">32</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="right">89</td>
<td align="right">66</td>
<td align="right">23</td>
<td align="right">94</td>
<td align="right">28.1</td>
<td align="right">0.167</td>
<td align="right">21</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">0</td>
<td align="right">137</td>
<td align="right">40</td>
<td align="right">35</td>
<td align="right">168</td>
<td align="right">43.1</td>
<td align="right">2.288</td>
<td align="right">33</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="right">5</td>
<td align="right">116</td>
<td align="right">74</td>
<td align="right">29</td>
<td align="right">125</td>
<td align="right">25.6</td>
<td align="right">0.201</td>
<td align="right">30</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p>For instance, I see that zero values in the insulin variable is replaced with median of insulin which is 125.</p>
<p>Now, the data is clean and ready for the modeling phase.</p>
<div id="modeling-the-data-build-fit-and-validate-a-model" class="section level3">
<h3>Modeling the data (build, fit and validate a model)</h3>
<p>Before going into any complicated model I am starting with a simple model to gain some insights about the data.</p>
<div id="linear-regression-model" class="section level4">
<h4>Linear Regression Model</h4>
<p>We will create two random subsets of our data in 80/20 proportion as <strong>training and test data.</strong>
Training data will be used to build our model and test data will be reserved to validate it.</p>
<pre class="r"><code># Create train test split
sample_rows &lt;- sample(nrow(diabetes), nrow(diabetes) * 0.8)
# Create the training dataset
dia_train &lt;- diabetes[sample_rows, ]
# Create the test dataset
dia_test &lt;- diabetes[-sample_rows, ]</code></pre>
<pre class="r"><code># Build a linear model with the train data
lm_dia &lt;- lm(Outcome ~ .,data = dia_train)
summary(lm_dia)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Outcome ~ ., data = dia_train)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.05292 -0.29280 -0.07527  0.29706  0.98070 
## 
## Coefficients:
##                            Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)              -1.0486126  0.1187838  -8.828  &lt; 2e-16 ***
## Pregnancies               0.0208532  0.0057346   3.636   0.0003 ***
## Glucose                   0.0063333  0.0006080  10.418  &lt; 2e-16 ***
## BloodPressure            -0.0009304  0.0015192  -0.612   0.5405    
## SkinThickness             0.0001233  0.0021496   0.057   0.9543    
## Insulin                  -0.0001146  0.0001989  -0.576   0.5647    
## BMI                       0.0152261  0.0030044   5.068 5.35e-07 ***
## DiabetesPedigreeFunction  0.1217518  0.0487052   2.500   0.0127 *  
## Age                       0.0023772  0.0016829   1.413   0.1583    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.3995 on 605 degrees of freedom
## Multiple R-squared:  0.3161, Adjusted R-squared:  0.307 
## F-statistic: 34.95 on 8 and 605 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code># We will predict the Outcome for the test data
p&lt;-predict(lm_dia, dia_test)
# Choose a threshold 0.5 to calculate the accuracy of our model
p_05 &lt;- ifelse(p &gt; 0.5, 1, 0)
table(p_05, dia_test$Outcome)</code></pre>
<pre><code>##     
## p_05  0  1
##    0 92 23
##    1 14 25</code></pre>
<pre class="r"><code>conf_mat &lt;- table(p_05, dia_test$Outcome)
accuracy &lt;- sum(diag(conf_mat))/sum(conf_mat)
accuracy</code></pre>
<pre><code>## [1] 0.7597403</code></pre>
<p>By using the pROC package, I will calculate the AUC value for our model.</p>
<pre class="r"><code># Calculate AUC
roc(dia_test$Outcome, p)</code></pre>
<pre><code>## Setting levels: control = 0, case = 1</code></pre>
<pre><code>## Setting direction: controls &lt; cases</code></pre>
<pre><code>## 
## Call:
## roc.default(response = dia_test$Outcome, predictor = p)
## 
## Data: p in 106 controls (dia_test$Outcome 0) &lt; 48 cases (dia_test$Outcome 1).
## Area under the curve: 0.8581</code></pre>
<p>If I repeat the above procedure, each time I will get a slightly different result depending on the given random train/test split. Depending on the outliers in the data you might get bigger differences.</p>
<p>We can run above model with 10/100/1000 different random splits to have a good estimate of the real accuracy.</p>
</div>
<div id="how-to-apply-linear-model-with-multiple-traintest-split" class="section level4">
<h4>How to apply linear model with multiple train/test split</h4>
<p>To do this, I will write a function where I can choose number of independent train/test splits.</p>
<p>It will return me an average value of the model after chosen number of iteration. The higher the number of random splits the more stable your estimated AUC.</p>
<p>Let’s see how it will work out for our diabetes patients.</p>
<pre class="r"><code># I will define my function as follows
multi_split &lt;- function(x){
sample_rows &lt;- list()
dia_train &lt;- list()
dia_test &lt;- list()
lm &lt;- list()
p &lt;-  list()
roc_auc &lt;- list()
for(i in 1:x){
  sample_rows[[i]] &lt;- sample(nrow(diabetes), nrow(diabetes) * 0.8)
  # Create the training dataset
  dia_train[[i]] &lt;- diabetes[sample_rows[[i]], ]
  # Create the test dataset
  dia_test[[i]] &lt;- diabetes[-sample_rows[[i]], ]
  lm[[i]] &lt;- lm(Outcome ~ .,data = dia_train[[i]])
  p[[i]] &lt;- predict(lm[[i]], dia_test[[i]])
  
  # Calculate AUC for all &quot;x&quot; number of random splits
  roc_auc[[i]] &lt;- roc(dia_test[[i]]$Outcome, p[[i]])$auc[1]
  lm_mean &lt;- mean(unlist(roc_auc))
}
print(mean(unlist(roc_auc)))
}</code></pre>
<p>Let’s calculate the average AUC of our model after different number of random splits.</p>
<p>I will run my multi_split functions 3x for 1, 30 and 1000 random train/test splits. I can then compare variances at each number of iteration.</p>
<pre class="r"><code>variance_1_1 &lt;- multi_split(1)</code></pre>
<pre><code>## [1] 0.8587037</code></pre>
<pre class="r"><code>variance_1_2 &lt;- multi_split(1)</code></pre>
<pre><code>## [1] 0.8709913</code></pre>
<pre class="r"><code>variance_1_3 &lt;- multi_split(1)</code></pre>
<pre><code>## [1] 0.7796143</code></pre>
<pre class="r"><code>variance_30_1 &lt;- multi_split(30)</code></pre>
<pre><code>## [1] 0.8333778</code></pre>
<pre class="r"><code>variance_30_2 &lt;- multi_split(30)</code></pre>
<pre><code>## [1] 0.8381756</code></pre>
<pre class="r"><code>variance_30_3 &lt;- multi_split(30)</code></pre>
<pre><code>## [1] 0.8501601</code></pre>
<pre class="r"><code>variance_1000_1 &lt;- multi_split(1000)</code></pre>
<pre><code>## [1] 0.8377785</code></pre>
<pre class="r"><code>variance_1000_2 &lt;- multi_split(1000)</code></pre>
<pre><code>## [1] 0.8359534</code></pre>
<pre class="r"><code>variance_1000_3 &lt;- multi_split(1000)</code></pre>
<pre><code>## [1] 0.8386704</code></pre>
<p>Let’s compare Variance levels at 1, 30 and 1000 random splits</p>
<pre class="r"><code>var(c(variance_1_1, variance_1_2, variance_1_3))</code></pre>
<pre><code>## [1] 0.002459309</code></pre>
<pre class="r"><code>var(c(variance_30_1, variance_30_2, variance_30_3))</code></pre>
<pre><code>## [1] 7.471549e-05</code></pre>
<pre class="r"><code>var(c(variance_1000_1, variance_1000_2, variance_1000_3))</code></pre>
<pre><code>## [1] 1.918109e-06</code></pre>
<p>What we see here as we increase the number of iterations to 30 and 1000 the variability
gradually stabilizes around a trustable AUC of <code>0.837</code>.</p>
</div>
</div>
<div id="build-a-logistic-regression-model" class="section level3">
<h3>Build a logistic regression model</h3>
<p>I will switch here to caret package. With the <strong>Train()</strong> function we can build and different types of machine learning algorithms.</p>
<p>I will start with a logistic regression model. But before I need to convert Outcome variable into a factor with 2 levels.</p>
<pre class="r"><code># Convert Outcome to a factor with two levels
diabetes$Outcome &lt;- factor(diabetes$Outcome)
levels(diabetes$Outcome) &lt;- c(&quot;H&quot;, &quot;D&quot;)

# MyControl
myControl &lt;- trainControl(
  method = &quot;cv&quot;, 
  number = 10,
  summaryFunction = twoClassSummary,
  classProbs = TRUE, # IMPORTANT!
  verboseIter = TRUE
)
# Model
model_glm &lt;- train(
  Outcome~.,
  method = &quot;glm&quot;,
  data = diabetes,
  trControl = myControl
)</code></pre>
<pre><code>## + Fold01: parameter=none 
## - Fold01: parameter=none 
## + Fold02: parameter=none 
## - Fold02: parameter=none 
## + Fold03: parameter=none 
## - Fold03: parameter=none 
## + Fold04: parameter=none 
## - Fold04: parameter=none 
## + Fold05: parameter=none 
## - Fold05: parameter=none 
## + Fold06: parameter=none 
## - Fold06: parameter=none 
## + Fold07: parameter=none 
## - Fold07: parameter=none 
## + Fold08: parameter=none 
## - Fold08: parameter=none 
## + Fold09: parameter=none 
## - Fold09: parameter=none 
## + Fold10: parameter=none 
## - Fold10: parameter=none 
## Aggregating results
## Fitting final model on full training set</code></pre>
<pre class="r"><code>model_glm</code></pre>
<pre><code>## Generalized Linear Model 
## 
## 768 samples
##   8 predictor
##   2 classes: &#39;H&#39;, &#39;D&#39; 
## 
## No pre-processing
## Resampling: Cross-Validated (10 fold) 
## Summary of sample sizes: 691, 691, 691, 691, 691, 691, ... 
## Resampling results:
## 
##   ROC        Sens   Spec     
##   0.8371225  0.884  0.5786325</code></pre>
<p>Here, My model performance is <code>0.8371225</code></p>
</div>
<div id="build-a-glmnet-model" class="section level3">
<h3>Build a glmnet model</h3>
<pre class="r"><code># Model
model_glmnet &lt;- train(
  Outcome~.,
  method = &quot;glmnet&quot;,
  data = diabetes,
  trControl = myControl
)</code></pre>
<pre class="r"><code>model_glmnet</code></pre>
<pre><code>## glmnet 
## 
## 768 samples
##   8 predictor
##   2 classes: &#39;H&#39;, &#39;D&#39; 
## 
## No pre-processing
## Resampling: Cross-Validated (10 fold) 
## Summary of sample sizes: 691, 691, 691, 691, 691, 691, ... 
## Resampling results across tuning parameters:
## 
##   alpha  lambda        ROC        Sens   Spec     
##   0.10   0.0004697604  0.8422849  0.880  0.5665242
##   0.10   0.0046976036  0.8430370  0.882  0.5626781
##   0.10   0.0469760360  0.8424786  0.892  0.5292023
##   0.55   0.0004697604  0.8419915  0.880  0.5665242
##   0.55   0.0046976036  0.8423077  0.882  0.5552707
##   0.55   0.0469760360  0.8410513  0.902  0.5180912
##   1.00   0.0004697604  0.8420655  0.880  0.5628205
##   1.00   0.0046976036  0.8428575  0.878  0.5552707
##   1.00   0.0469760360  0.8307037  0.906  0.4957265
## 
## ROC was used to select the optimal model using the largest value.
## The final values used for the model were alpha = 0.1 and lambda
##  = 0.004697604.</code></pre>
<p>Glmnet model performance is <code>0.843037</code></p>
</div>
<div id="build-a-random-forest-model" class="section level3">
<h3>Build a Random forest model</h3>
<pre class="r"><code># Random forest model
model_rf &lt;- train(
  Outcome~.,
  method = &quot;ranger&quot;,
  data = diabetes,
  trControl = myControl
  )</code></pre>
<pre class="r"><code>model_rf</code></pre>
<pre><code>## Random Forest 
## 
## 768 samples
##   8 predictor
##   2 classes: &#39;H&#39;, &#39;D&#39; 
## 
## No pre-processing
## Resampling: Cross-Validated (10 fold) 
## Summary of sample sizes: 691, 691, 691, 691, 691, 691, ... 
## Resampling results across tuning parameters:
## 
##   mtry  splitrule   ROC        Sens   Spec     
##   2     gini        0.8314587  0.848  0.6123932
##   2     extratrees  0.8373362  0.862  0.5934473
##   5     gini        0.8248077  0.834  0.6529915
##   5     extratrees  0.8311524  0.852  0.6121083
##   8     gini        0.8234786  0.832  0.6529915
##   8     extratrees  0.8284943  0.848  0.6156695
## 
## Tuning parameter &#39;min.node.size&#39; was held constant at a value of 1
## ROC was used to select the optimal model using the largest value.
## The final values used for the model were mtry = 2, splitrule =
##  extratrees and min.node.size = 1.</code></pre>
<p>Random forest performance is <code>0.8373362</code></p>
</div>
</div>
<div id="build-a-gradient-boost-model" class="section level1">
<h1>Build a Gradient boost model</h1>
<pre class="r"><code>model_gbm &lt;- train(
    Outcome~.,
    method = &quot;gbm&quot;,
    data = diabetes,
    trControl = myControl
)</code></pre>
<pre class="r"><code>model_gbm</code></pre>
<pre><code>## Stochastic Gradient Boosting 
## 
## 768 samples
##   8 predictor
##   2 classes: &#39;H&#39;, &#39;D&#39; 
## 
## No pre-processing
## Resampling: Cross-Validated (10 fold) 
## Summary of sample sizes: 692, 691, 691, 691, 691, 691, ... 
## Resampling results across tuning parameters:
## 
##   interaction.depth  n.trees  ROC        Sens   Spec     
##   1                   50      0.8405670  0.890  0.5715100
##   1                  100      0.8468205  0.874  0.5784900
##   1                  150      0.8478575  0.874  0.5971510
##   2                   50      0.8444245  0.866  0.5787749
##   2                  100      0.8386382  0.850  0.6084046
##   2                  150      0.8338718  0.842  0.5709402
##   3                   50      0.8407863  0.860  0.5934473
##   3                  100      0.8367949  0.850  0.5971510
##   3                  150      0.8265499  0.844  0.5968661
## 
## Tuning parameter &#39;shrinkage&#39; was held constant at a value of 0.1
## 
## Tuning parameter &#39;n.minobsinnode&#39; was held constant at a value of 10
## ROC was used to select the optimal model using the largest value.
## The final values used for the model were n.trees = 150,
##  interaction.depth = 1, shrinkage = 0.1 and n.minobsinnode = 10.</code></pre>
<p>Gradient boost model performance is <code>0.8478575</code></p>
</div>
<div id="build-a-model-with-naive-bayes-algorithm" class="section level1">
<h1>Build a model with Naive Bayes algorithm</h1>
<pre class="r"><code>model_nb &lt;- train(
    Outcome~.,
    method = &quot;nb&quot;,
    data = diabetes,
    trControl = myControl
)</code></pre>
<pre class="r"><code>model_nb</code></pre>
<pre><code>## Naive Bayes 
## 
## 768 samples
##   8 predictor
##   2 classes: &#39;H&#39;, &#39;D&#39; 
## 
## No pre-processing
## Resampling: Cross-Validated (10 fold) 
## Summary of sample sizes: 691, 691, 691, 692, 691, 691, ... 
## Resampling results across tuning parameters:
## 
##   usekernel  ROC        Sens   Spec     
##   FALSE      0.8118519  0.826  0.5930199
##    TRUE      0.8141368  0.822  0.6158120
## 
## Tuning parameter &#39;fL&#39; was held constant at a value of 0
## Tuning
##  parameter &#39;adjust&#39; was held constant at a value of 1
## ROC was used to select the optimal model using the largest value.
## The final values used for the model were fL = 0, usekernel = TRUE
##  and adjust = 1.</code></pre>
<p>Naive Bayes model performance is <code>0.8141368</code></p>
<pre class="r"><code>models &lt;- c(&quot;lm&quot;, &quot;glm&quot;, &quot;glmnet&quot;, &quot;rf&quot;, &quot;gbm&quot;, &quot;naive&quot;)
lm &lt;- round(mean(c(variance_1000_1, variance_1000_2, variance_1000_3)), 3)
glm &lt;- max(model_glm$results$ROC)
glmnet &lt;- max(model_glmnet$results$ROC)
rf &lt;- max(model_rf$results$ROC)
gbm &lt;- max(model_gbm$results$ROC)
naive &lt;- max(model_nb$results$ROC)
AUC &lt;- c(lm, glm, glmnet, rf, gbm, naive)
df &lt;- data.frame(models, AUC)
df[order(df[,2], decreasing=TRUE), ]</code></pre>
<pre><code>##   models       AUC
## 5    gbm 0.8478575
## 3 glmnet 0.8430370
## 4     rf 0.8373362
## 2    glm 0.8371225
## 1     lm 0.8370000
## 6  naive 0.8141368</code></pre>
<p>Here, we found Gradient boost model performed the best, but there is not big difference between the models.</p>
<div id="future-thoughts" class="section level2">
<h2>Future thoughts</h2>
<p>Here, I utilized different machine learning algorithms to predict Diabetes diagnosis. I didn’t find big difference between the models except the naives bayes which performed worst here. As we saw, sometimes a simple model can get us far.</p>
<p>We can help doctors to predict <strong>Diabetes with accuracy around 84%</strong> by using 8 simple medical parameters.</p>
<p>Given current speed in generation and collection of types data by including additonal predictors we can build even better models.</p>
<p>Until next time!</p>
<p>Serdar</p>
</div>
</div>

    </div>

    


    

<div class="article-tags">
  
  <a class="badge badge-light" href="/tags/machine-learning/">Machine learning</a>
  
  <a class="badge badge-light" href="/tags/blog/">Blog</a>
  
  <a class="badge badge-light" href="/tags/data-science-process/">Data Science Process</a>
  
  <a class="badge badge-light" href="/tags/linear-regression/">Linear Regression</a>
  
  <a class="badge badge-light" href="/tags/logistic-regression/">Logistic Regression</a>
  
  <a class="badge badge-light" href="/tags/glmnet/">glmnet</a>
  
  <a class="badge badge-light" href="/tags/randomforest/">Randomforest</a>
  
  <a class="badge badge-light" href="/tags/data-quality-control/">Data Quality control</a>
  
  <a class="badge badge-light" href="/tags/feature-engineering/">Feature engineering</a>
  
  <a class="badge badge-light" href="/tags/pima-indians/">Pima Indians</a>
  
</div>



    
      








  






  
  
  
    
  
  
  <div class="media author-card">
    
      
      <img class="portrait mr-3" src="/authors/admin/avatar_huc20273ad926c00177316852a0ac5eb17_12606_250x250_fill_q90_lanczos_center.jpg" alt="Avatar">
    

    <div class="media-body">
      <h5 class="card-title"><a href="/">Serdar Korur</a></h5>
      <h6 class="card-subtitle">Senior Scientist in Drug Discovery</h6>
      <p class="card-text">Serdar is a Data Scientist and PhD in Cell Biology</p>
      <ul class="network-icon" aria-hidden="true">
        
          
          
          
            
          
          
          
          
          
            
          
          <li>
            <a href="/#contact" >
              <i class="fas fa-envelope"></i>
            </a>
          </li>
        
          
          
          
            
          
          
          
          
          
            
          
          <li>
            <a href="https://www.linkedin.com/in/serdar-korur/" target="_blank" rel="noopener">
              <i class="fab fa-linkedin"></i>
            </a>
          </li>
        
          
          
          
            
          
          
          
          
          
            
          
          <li>
            <a href="https://github.com/korur/" target="_blank" rel="noopener">
              <i class="fab fa-github"></i>
            </a>
          </li>
        
      </ul>
    </div>
  </div>



      
      
      <div class="article-widget">
        <div class="hr-light"></div>
        <h3>Related</h3>
        <ul>
          
          <li><a href="/2019/09/15/deploy-your-blog-in-5-minutes/">Set up and deploy your blog in 5 minutes on Netlify with Hugo and blogdown (September 2019 Update)</a></li>
          
        </ul>
      </div>
      
    

    

    
<section id="comments">
  
    
<div id="disqus_thread"></div>
<script>
  let disqus_config = function () {
    
    
    
  };
  (function() {
    if (["localhost", "127.0.0.1"].indexOf(window.location.hostname) != -1) {
      document.getElementById('disqus_thread').innerHTML = 'Disqus comments not available by default when the website is previewed locally.';
      return;
    }
    var d = document, s = d.createElement('script'); s.async = true;
    s.src = 'https://' + "serdarkorur" + '.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="https://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>


  
</section>



  </div>
</article>

      

    
    
    
    <script src="/js/mathjax-config.js"></script>
    

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.js" integrity="sha256-X5PoE3KU5l+JcX+w09p/wHl9AzK333C4hJ2I9S5mD4M=" crossorigin="anonymous"></script>

      

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/highlight.min.js" integrity="sha256-aYTdUrn6Ow1DDgh5JTc3aDGnnju48y/1c8s1dgkYPQ8=" crossorigin="anonymous"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/languages/r.min.js"></script>
        
      

      
      
      <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS_CHTML-full" integrity="sha256-GhM+5JHb6QUzOQPXSJLEWP7R73CbkisjzK5Eyij4U9w=" crossorigin="anonymous" async></script>
      
    

    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.2.0/leaflet.js" integrity="sha512-lInM/apFSqyy1o6s89K4iQUKg6ppXEgsVxT35HbzUupEVRh2Eu9Wdl4tHj7dZO0s1uvplcYGmt3498TtHq+log==" crossorigin="anonymous"></script>
    

    
    
    <script>hljs.initHighlightingOnLoad();</script>
    

    
    
    <script>
      const search_index_filename = "/index.json";
      const i18n = {
        'placeholder': "Search...",
        'results': "results found",
        'no_results': "No results found"
      };
      const content_type = {
        'post': "Posts",
        'project': "Projects",
        'publication' : "Publications",
        'talk' : "Talks"
        };
    </script>
    

    
    

    
    
    <script id="search-hit-fuse-template" type="text/x-template">
      <div class="search-hit" id="summary-{{key}}">
      <div class="search-hit-content">
        <div class="search-hit-name">
          <a href="{{relpermalink}}">{{title}}</a>
          <div class="article-metadata search-hit-type">{{type}}</div>
          <p class="search-hit-description">{{snippet}}</p>
        </div>
      </div>
      </div>
    </script>
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.2.1/fuse.min.js" integrity="sha256-VzgmKYmhsGNNN4Ph1kMW+BjoYJM2jV5i4IlFoeZA9XI=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script>
    

    
    

    
    
    <script id="dsq-count-scr" src="https://serdarkorur.disqus.com/count.js" async></script>
    

    
    
    
    
    
    
    
    
    
      
    
    
    
    
    <script src="/js/academic.min.130521ecfc6f534c52c158217bbff718.js"></script>

    






  
  <div class="container">
    <footer class="site-footer">
  
  <p class="powered-by">
    
      <a href="/privacy/">Privacy Policy</a>
    
    
       &middot; 
      <a href="/terms/">Terms</a>
        
  </p>
  

  <p class="powered-by">
    

    Powered by the
    <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> for
    <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a>.

    
    <span class="float-right" aria-hidden="true">
      <a href="#" id="back_to_top">
        <span class="button_icon">
          <i class="fas fa-chevron-up fa-2x"></i>
        </span>
      </a>
    </span>
    
  </p>
</footer>

  </div>
  

  
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

</body>
</html>
